<?php

namespace Bordeux\SchemaOrg\Thing\CreativeWork\Article\ScholarlyArticle;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/MedicalScholarlyArticle
 *
 *
 * -------------------------------- PublicationType ---------------------------------------------
 *
 * @property string PublicationType
 *
 * @method string getPublicationType() The type of the medical article, taken from the US NLM MeSH publication type catalog.
 *
 * @method MedicalScholarlyArticle setPublicationType(string $publicationType )The type of the medical article, taken from the US NLM MeSH publication type catalog.
 *
 *
 */
class MedicalScholarlyArticle extends \Bordeux\SchemaOrg\Thing\CreativeWork\Article\ScholarlyArticle
{
}
