<?php

namespace Bordeux\SchemaOrg\Thing\Intangible\StructuredValue;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/NutritionInformation
 *
 *
 * -------------------------------- Calories ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Energy Calories
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Energy getCalories() The number of calories
 *
 * @method NutritionInformation setCalories(\Bordeux\SchemaOrg\Thing\Intangible\Quantity\Energy $calories )The number of calories
 *
 *
 * -------------------------------- CarbohydrateContent ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass CarbohydrateContent
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass getCarbohydrateContent() The number of grams of carbohydrates.
 *
 * @method NutritionInformation setCarbohydrateContent(\Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass $carbohydrateContent )The number of grams of carbohydrates.
 *
 *
 * -------------------------------- CholesterolContent ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass CholesterolContent
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass getCholesterolContent() The number of milligrams of cholesterol.
 *
 * @method NutritionInformation setCholesterolContent(\Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass $cholesterolContent )The number of milligrams of cholesterol.
 *
 *
 * -------------------------------- FatContent ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass FatContent
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass getFatContent() The number of grams of fat.
 *
 * @method NutritionInformation setFatContent(\Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass $fatContent )The number of grams of fat.
 *
 *
 * -------------------------------- FiberContent ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass FiberContent
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass getFiberContent() The number of grams of fiber.
 *
 * @method NutritionInformation setFiberContent(\Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass $fiberContent )The number of grams of fiber.
 *
 *
 * -------------------------------- ProteinContent ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass ProteinContent
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass getProteinContent() The number of grams of protein.
 *
 * @method NutritionInformation setProteinContent(\Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass $proteinContent )The number of grams of protein.
 *
 *
 * -------------------------------- SaturatedFatContent ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass SaturatedFatContent
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass getSaturatedFatContent() The number of grams of saturated fat.
 *
 * @method NutritionInformation setSaturatedFatContent(\Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass $saturatedFatContent )The number of grams of saturated fat.
 *
 *
 * -------------------------------- ServingSize ---------------------------------------------
 *
 * @property string ServingSize
 *
 * @method string getServingSize() The serving size, in terms of the number of volume or mass
 *
 * @method NutritionInformation setServingSize(string $servingSize )The serving size, in terms of the number of volume or mass
 *
 *
 * -------------------------------- SodiumContent ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass SodiumContent
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass getSodiumContent() The number of milligrams of sodium.
 *
 * @method NutritionInformation setSodiumContent(\Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass $sodiumContent )The number of milligrams of sodium.
 *
 *
 * -------------------------------- SugarContent ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass SugarContent
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass getSugarContent() The number of grams of sugar.
 *
 * @method NutritionInformation setSugarContent(\Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass $sugarContent )The number of grams of sugar.
 *
 *
 * -------------------------------- TransFatContent ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass TransFatContent
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass getTransFatContent() The number of grams of trans fat.
 *
 * @method NutritionInformation setTransFatContent(\Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass $transFatContent )The number of grams of trans fat.
 *
 *
 * -------------------------------- UnsaturatedFatContent ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass UnsaturatedFatContent
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass getUnsaturatedFatContent() The number of grams of unsaturated fat.
 *
 * @method NutritionInformation setUnsaturatedFatContent(\Bordeux\SchemaOrg\Thing\Intangible\Quantity\Mass $unsaturatedFatContent )The number of grams of unsaturated fat.
 *
 *
 */
class NutritionInformation extends \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue
{
}
