<?php

namespace Bordeux\SchemaOrg\Thing\CreativeWork;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/Article
 *
 *
 * -------------------------------- ArticleBody ---------------------------------------------
 *
 * @property string ArticleBody
 *
 * @method string getArticleBody() The actual body of the article.
 *
 * @method Article setArticleBody(string $articleBody )The actual body of the article.
 *
 *
 * -------------------------------- ArticleSection ---------------------------------------------
 *
 * @property string ArticleSection
 *
 * @method string getArticleSection() Articles may belong to one or more 'sections' in a magazine or newspaper, such as Sports, Lifestyle, etc.
 *
 * @method Article setArticleSection(string $articleSection )Articles may belong to one or more 'sections' in a magazine or newspaper, such as Sports, Lifestyle, etc.
 *
 *
 * -------------------------------- WordCount ---------------------------------------------
 *
 * @property Integer WordCount
 *
 * @method Integer getWordCount() The number of words in the text of the Article.
 *
 * @method Article setWordCount(Integer $wordCount )The number of words in the text of the Article.
 *
 *
 */
class Article extends \Bordeux\SchemaOrg\Thing\CreativeWork
{
}
