<?php

namespace Bordeux\SchemaOrg\Thing\CreativeWork;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/Code
 *
 *
 * -------------------------------- CodeRepository ---------------------------------------------
 *
 * @property string CodeRepository
 *
 * @method string getCodeRepository() Link to the repository where the un-compiled, human readable code and related code is located (SVN, github, CodePlex)
 *
 * @method Code setCodeRepository(string $codeRepository )Link to the repository where the un-compiled, human readable code and related code is located (SVN, github, CodePlex)
 *
 *
 * -------------------------------- ProgrammingLanguage ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing ProgrammingLanguage
 *
 * @method \Bordeux\SchemaOrg\Thing getProgrammingLanguage() The computer programming language.
 *
 * @method Code setProgrammingLanguage(\Bordeux\SchemaOrg\Thing $programmingLanguage )The computer programming language.
 *
 *
 * -------------------------------- Runtime ---------------------------------------------
 *
 * @property string Runtime
 *
 * @method string getRuntime() Runtime platform or script interpreter dependencies (Example - Java v1, Python2.3, .Net Framework 3.0)
 *
 * @method Code setRuntime(string $runtime )Runtime platform or script interpreter dependencies (Example - Java v1, Python2.3, .Net Framework 3.0)
 *
 *
 * -------------------------------- SampleType ---------------------------------------------
 *
 * @property string SampleType
 *
 * @method string getSampleType() Full (compile ready) solution, code snippet, inline code, scripts, template.
 *
 * @method Code setSampleType(string $sampleType )Full (compile ready) solution, code snippet, inline code, scripts, template.
 *
 *
 * -------------------------------- TargetProduct ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\CreativeWork\SoftwareApplication TargetProduct
 *
 * @method \Bordeux\SchemaOrg\Thing\CreativeWork\SoftwareApplication getTargetProduct() Target Operating System / Product to which the code applies.  If applies to several versions, just the product name can be used.
 *
 * @method Code setTargetProduct(\Bordeux\SchemaOrg\Thing\CreativeWork\SoftwareApplication $targetProduct )Target Operating System / Product to which the code applies.  If applies to several versions, just the product name can be used.
 *
 *
 */
class Code extends \Bordeux\SchemaOrg\Thing\CreativeWork
{
}
