<?php

namespace Bordeux\SchemaOrg\Thing\CreativeWork;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/ItemList
 *
 *
 * -------------------------------- ItemListElement ---------------------------------------------
 *
 * @property string ItemListElement
 *
 * @method string getItemListElement() A single list item.
 *
 * @method ItemList setItemListElement(string $itemListElement )A single list item.
 *
 *
 * -------------------------------- ItemListOrder ---------------------------------------------
 *
 * @property string ItemListOrder
 *
 * @method string getItemListOrder() Type of ordering (e.g. Ascending, Descending, Unordered).
 *
 * @method ItemList setItemListOrder(string $itemListOrder )Type of ordering (e.g. Ascending, Descending, Unordered).
 *
 *
 */
class ItemList extends \Bordeux\SchemaOrg\Thing\CreativeWork
{
}
