<?php

namespace Bordeux\SchemaOrg\Thing\CreativeWork;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/Recipe
 *
 *
 * -------------------------------- CookingMethod ---------------------------------------------
 *
 * @property string CookingMethod
 *
 * @method string getCookingMethod() The method of cooking, such as Frying, Steaming, ...
 *
 * @method Recipe setCookingMethod(string $cookingMethod )The method of cooking, such as Frying, Steaming, ...
 *
 *
 * -------------------------------- CookTime ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Duration CookTime
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Duration getCookTime() The time it takes to actually cook the dish, in ISO 8601 duration format.
 *
 * @method Recipe setCookTime(\Bordeux\SchemaOrg\Thing\Intangible\Quantity\Duration $cookTime )The time it takes to actually cook the dish, in ISO 8601 duration format.
 *
 *
 * -------------------------------- Ingredients ---------------------------------------------
 *
 * @property string Ingredients
 *
 * @method string getIngredients() An ingredient used in the recipe.
 *
 * @method Recipe setIngredients(string $ingredients )An ingredient used in the recipe.
 *
 *
 * -------------------------------- Nutrition ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\NutritionInformation Nutrition
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\NutritionInformation getNutrition() Nutrition information about the recipe.
 *
 * @method Recipe setNutrition(\Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\NutritionInformation $nutrition )Nutrition information about the recipe.
 *
 *
 * -------------------------------- PrepTime ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Duration PrepTime
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Duration getPrepTime() The length of time it takes to prepare the recipe, in ISO 8601 duration format.
 *
 * @method Recipe setPrepTime(\Bordeux\SchemaOrg\Thing\Intangible\Quantity\Duration $prepTime )The length of time it takes to prepare the recipe, in ISO 8601 duration format.
 *
 *
 * -------------------------------- RecipeCategory ---------------------------------------------
 *
 * @property string RecipeCategory
 *
 * @method string getRecipeCategory() The category of the recipe—for example, appetizer, entree, etc.
 *
 * @method Recipe setRecipeCategory(string $recipeCategory )The category of the recipe—for example, appetizer, entree, etc.
 *
 *
 * -------------------------------- RecipeCuisine ---------------------------------------------
 *
 * @property string RecipeCuisine
 *
 * @method string getRecipeCuisine() The cuisine of the recipe (for example, French or Ethopian).
 *
 * @method Recipe setRecipeCuisine(string $recipeCuisine )The cuisine of the recipe (for example, French or Ethopian).
 *
 *
 * -------------------------------- RecipeInstructions ---------------------------------------------
 *
 * @property string RecipeInstructions
 *
 * @method string getRecipeInstructions() The steps to make the dish.
 *
 * @method Recipe setRecipeInstructions(string $recipeInstructions )The steps to make the dish.
 *
 *
 * -------------------------------- RecipeYield ---------------------------------------------
 *
 * @property string RecipeYield
 *
 * @method string getRecipeYield() The quantity produced by the recipe (for example, number of people served, number of servings, etc).
 *
 * @method Recipe setRecipeYield(string $recipeYield )The quantity produced by the recipe (for example, number of people served, number of servings, etc).
 *
 *
 * -------------------------------- TotalTime ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Duration TotalTime
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Duration getTotalTime() The total time it takes to prepare and cook the recipe, in ISO 8601 duration format.
 *
 * @method Recipe setTotalTime(\Bordeux\SchemaOrg\Thing\Intangible\Quantity\Duration $totalTime )The total time it takes to prepare and cook the recipe, in ISO 8601 duration format.
 *
 *
 */
class Recipe extends \Bordeux\SchemaOrg\Thing\CreativeWork
{
}
