<?php

namespace Bordeux\SchemaOrg\Thing\CreativeWork;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/Season
 *
 *
 * -------------------------------- EndDate ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\SchemaDateTime EndDate
 *
 * @method \Bordeux\SchemaOrg\SchemaDateTime getEndDate() The end date and time of the event or item (in ISO 8601 date format).
 *
 * @method Season setEndDate(\Bordeux\SchemaOrg\SchemaDateTime $endDate )The end date and time of the event or item (in ISO 8601 date format).
 *
 *
 * -------------------------------- Episode ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\CreativeWork\Episode Episode
 *
 * @method \Bordeux\SchemaOrg\Thing\CreativeWork\Episode getEpisode() An episode of a TV/radio series or season
 *
 * @method Season setEpisode(\Bordeux\SchemaOrg\Thing\CreativeWork\Episode $episode )An episode of a TV/radio series or season
 *
 *
 * -------------------------------- Episodes ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\CreativeWork\Episode Episodes
 *
 * @method \Bordeux\SchemaOrg\Thing\CreativeWork\Episode getEpisodes() An episode of a TV/radio series or season (legacy spelling; see singular form, episode)
 *
 * @method Season setEpisodes(\Bordeux\SchemaOrg\Thing\CreativeWork\Episode $episodes )An episode of a TV/radio series or season (legacy spelling; see singular form, episode)
 *
 *
 * -------------------------------- NumberOfEpisodes ---------------------------------------------
 *
 * @property Number NumberOfEpisodes
 *
 * @method Number getNumberOfEpisodes() The number of episodes in this season or series.
 *
 * @method Season setNumberOfEpisodes(Number $numberOfEpisodes )The number of episodes in this season or series.
 *
 *
 * -------------------------------- PartOfSeries ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\CreativeWork\Series PartOfSeries
 *
 * @method \Bordeux\SchemaOrg\Thing\CreativeWork\Series getPartOfSeries() The series to which this episode or season belongs.
 *
 * @method Season setPartOfSeries(\Bordeux\SchemaOrg\Thing\CreativeWork\Series $partOfSeries )The series to which this episode or season belongs.
 *
 *
 * -------------------------------- Position ---------------------------------------------
 *
 * @property string Position
 *
 * @method string getPosition() Free text to define other than pure numerical ranking of an episode or a season in an ordered list of items (further formatting restrictions may apply within particular user groups).
 *
 * @method Season setPosition(string $position )Free text to define other than pure numerical ranking of an episode or a season in an ordered list of items (further formatting restrictions may apply within particular user groups).
 *
 *
 * -------------------------------- Producer ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Person Producer
 *
 * @method \Bordeux\SchemaOrg\Thing\Person getProducer() The producer of the movie, tv/radio series, season, or episode, or video.
 *
 * @method Season setProducer(\Bordeux\SchemaOrg\Thing\Person $producer )The producer of the movie, tv/radio series, season, or episode, or video.
 *
 *
 * -------------------------------- ProductionCompany ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Organization ProductionCompany
 *
 * @method \Bordeux\SchemaOrg\Thing\Organization getProductionCompany() The production company or studio that made the movie, tv/radio series, season, or episode, or media object.
 *
 * @method Season setProductionCompany(\Bordeux\SchemaOrg\Thing\Organization $productionCompany )The production company or studio that made the movie, tv/radio series, season, or episode, or media object.
 *
 *
 * -------------------------------- SeasonNumber ---------------------------------------------
 *
 * @property Integer SeasonNumber
 *
 * @method Integer getSeasonNumber() Position of the season within an ordered group of seasons.
 *
 * @method Season setSeasonNumber(Integer $seasonNumber )Position of the season within an ordered group of seasons.
 *
 *
 * -------------------------------- StartDate ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\SchemaDateTime StartDate
 *
 * @method \Bordeux\SchemaOrg\SchemaDateTime getStartDate() The start date and time of the event or item (in ISO 8601 date format).
 *
 * @method Season setStartDate(\Bordeux\SchemaOrg\SchemaDateTime $startDate )The start date and time of the event or item (in ISO 8601 date format).
 *
 *
 * -------------------------------- Trailer ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\VideoObject Trailer
 *
 * @method \Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\VideoObject getTrailer() The trailer of a movie or tv/radio series, season, or episode.
 *
 * @method Season setTrailer(\Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\VideoObject $trailer )The trailer of a movie or tv/radio series, season, or episode.
 *
 *
 */
class Season extends \Bordeux\SchemaOrg\Thing\CreativeWork
{
}
