<?php

namespace Bordeux\SchemaOrg\Thing\Intangible;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/Brand
 *
 *
 * -------------------------------- Logo ---------------------------------------------
 *
 * @property string|\Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\ImageObject Logo
 *
 * @method string|\Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\ImageObject getLogo() A logo associated with an organization.
 *
 * @method Brand setLogo(string $logo ) setLogo(\Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\ImageObject $logo )A logo associated with an organization.
 *
 *
 */
class Brand extends \Bordeux\SchemaOrg\Thing\Intangible
{
}
