<?php

namespace Bordeux\SchemaOrg\Thing\Intangible;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/Permit
 *
 *
 * -------------------------------- IssuedBy ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Organization IssuedBy
 *
 * @method \Bordeux\SchemaOrg\Thing\Organization getIssuedBy() The organization issuing the permit.
 *
 * @method Permit setIssuedBy(\Bordeux\SchemaOrg\Thing\Organization $issuedBy )The organization issuing the permit.
 *
 *
 * -------------------------------- IssuedThrough ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Service IssuedThrough
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Service getIssuedThrough() The service through with the permit was granted.
 *
 * @method Permit setIssuedThrough(\Bordeux\SchemaOrg\Thing\Intangible\Service $issuedThrough )The service through with the permit was granted.
 *
 *
 * -------------------------------- PermitAudience ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Audience PermitAudience
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Audience getPermitAudience() The target audience for this permit.
 *
 * @method Permit setPermitAudience(\Bordeux\SchemaOrg\Thing\Intangible\Audience $permitAudience )The target audience for this permit.
 *
 *
 * -------------------------------- ValidFor ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Duration ValidFor
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Quantity\Duration getValidFor() The time validity of the permit.
 *
 * @method Permit setValidFor(\Bordeux\SchemaOrg\Thing\Intangible\Quantity\Duration $validFor )The time validity of the permit.
 *
 *
 * -------------------------------- ValidFrom ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\SchemaDateTime ValidFrom
 *
 * @method \Bordeux\SchemaOrg\SchemaDateTime getValidFrom() The date when the item becomes valid.
 *
 * @method Permit setValidFrom(\Bordeux\SchemaOrg\SchemaDateTime $validFrom )The date when the item becomes valid.
 *
 *
 * -------------------------------- ValidIn ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Place\AdministrativeArea ValidIn
 *
 * @method \Bordeux\SchemaOrg\Thing\Place\AdministrativeArea getValidIn() The geographic area where the permit is valid.
 *
 * @method Permit setValidIn(\Bordeux\SchemaOrg\Thing\Place\AdministrativeArea $validIn )The geographic area where the permit is valid.
 *
 *
 * -------------------------------- ValidUntil ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\SchemaDateTime ValidUntil
 *
 * @method \Bordeux\SchemaOrg\SchemaDateTime getValidUntil() The date when the item is no longer valid.
 *
 * @method Permit setValidUntil(\Bordeux\SchemaOrg\SchemaDateTime $validUntil )The date when the item is no longer valid.
 *
 *
 */
class Permit extends \Bordeux\SchemaOrg\Thing\Intangible
{
}
