<?php

namespace Bordeux\SchemaOrg\Thing\Intangible;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/Service
 *
 *
 * -------------------------------- AvailableChannel ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\ServiceChannel AvailableChannel
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\ServiceChannel getAvailableChannel() A means of accessing the service (e.g. a phone bank, a web site, a location, etc.)
 *
 * @method Service setAvailableChannel(\Bordeux\SchemaOrg\Thing\Intangible\ServiceChannel $availableChannel )A means of accessing the service (e.g. a phone bank, a web site, a location, etc.)
 *
 *
 * -------------------------------- Produces ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing Produces
 *
 * @method \Bordeux\SchemaOrg\Thing getProduces() The tangible thing generated by the service, e.g. a passport, permit, etc.
 *
 * @method Service setProduces(\Bordeux\SchemaOrg\Thing $produces )The tangible thing generated by the service, e.g. a passport, permit, etc.
 *
 *
 * -------------------------------- Provider ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Organization|\Bordeux\SchemaOrg\Thing\Person Provider
 *
 * @method \Bordeux\SchemaOrg\Thing\Organization|\Bordeux\SchemaOrg\Thing\Person getProvider() The organization or agency that is providing the service.
 *
 * @method Service setProvider(\Bordeux\SchemaOrg\Thing\Organization $provider ) setProvider(\Bordeux\SchemaOrg\Thing\Person $provider )The organization or agency that is providing the service.
 *
 *
 * -------------------------------- ServiceArea ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Place\AdministrativeArea ServiceArea
 *
 * @method \Bordeux\SchemaOrg\Thing\Place\AdministrativeArea getServiceArea() The geographic area where the service is provided.
 *
 * @method Service setServiceArea(\Bordeux\SchemaOrg\Thing\Place\AdministrativeArea $serviceArea )The geographic area where the service is provided.
 *
 *
 * -------------------------------- ServiceAudience ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Audience ServiceAudience
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Audience getServiceAudience() The audience eligible for this service.
 *
 * @method Service setServiceAudience(\Bordeux\SchemaOrg\Thing\Intangible\Audience $serviceAudience )The audience eligible for this service.
 *
 *
 * -------------------------------- ServiceType ---------------------------------------------
 *
 * @property string ServiceType
 *
 * @method string getServiceType() The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
 *
 * @method Service setServiceType(string $serviceType )The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
 *
 *
 */
class Service extends \Bordeux\SchemaOrg\Thing\Intangible
{
}
