<?php

namespace Bordeux\SchemaOrg\Thing\Intangible\Audience;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/EducationalAudience
 *
 *
 * -------------------------------- EducationalRole ---------------------------------------------
 *
 * @property string EducationalRole
 *
 * @method string getEducationalRole() An educationalRole of an EducationalAudience
 *
 * @method EducationalAudience setEducationalRole(string $educationalRole )An educationalRole of an EducationalAudience
 *
 *
 */
class EducationalAudience extends \Bordeux\SchemaOrg\Thing\Intangible\Audience
{
}
