<?php

namespace Bordeux\SchemaOrg\Thing\Action\TransferAction;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/LendAction
 *
 *
 * -------------------------------- Borrower ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Person Borrower
 *
 * @method \Bordeux\SchemaOrg\Thing\Person getBorrower() A sub property of participant. The person that borrows the object being lent.
 *
 * @method LendAction setBorrower(\Bordeux\SchemaOrg\Thing\Person $borrower )A sub property of participant. The person that borrows the object being lent.
 *
 *
 */
class LendAction extends \Bordeux\SchemaOrg\Thing\Action\TransferAction
{
}
