<?php

namespace Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalStudy;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/MedicalTrial
 *
 *
 * -------------------------------- Phase ---------------------------------------------
 *
 * @property string Phase
 *
 * @method string getPhase() The phase of the trial.
 *
 * @method MedicalTrial setPhase(string $phase )The phase of the trial.
 *
 *
 * -------------------------------- TrialDesign ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible\MedicalEnumeration\MedicalTrialDesign TrialDesign
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible\MedicalEnumeration\MedicalTrialDesign getTrialDesign() Specifics about the trial design (enumerated).
 *
 * @method MedicalTrial setTrialDesign(\Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible\MedicalEnumeration\MedicalTrialDesign $trialDesign )Specifics about the trial design (enumerated).
 *
 *
 */
class MedicalTrial extends \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalStudy
{
}
