<?php

namespace Bordeux\SchemaOrg\Thing\CreativeWork\Article;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/NewsArticle
 *
 *
 * -------------------------------- Dateline ---------------------------------------------
 *
 * @property string Dateline
 *
 * @method string getDateline() The location where the NewsArticle was produced.
 *
 * @method NewsArticle setDateline(string $dateline )The location where the NewsArticle was produced.
 *
 *
 * -------------------------------- PrintColumn ---------------------------------------------
 *
 * @property string PrintColumn
 *
 * @method string getPrintColumn() The number of the column in which the NewsArticle appears in the print edition.
 *
 * @method NewsArticle setPrintColumn(string $printColumn )The number of the column in which the NewsArticle appears in the print edition.
 *
 *
 * -------------------------------- PrintEdition ---------------------------------------------
 *
 * @property string PrintEdition
 *
 * @method string getPrintEdition() The edition of the print product in which the NewsArticle appears.
 *
 * @method NewsArticle setPrintEdition(string $printEdition )The edition of the print product in which the NewsArticle appears.
 *
 *
 * -------------------------------- PrintPage ---------------------------------------------
 *
 * @property string PrintPage
 *
 * @method string getPrintPage() If this NewsArticle appears in print, this field indicates the name of the page on which the article is found. Please note that this field is intended for the exact page name (e.g. A5, B18).
 *
 * @method NewsArticle setPrintPage(string $printPage )If this NewsArticle appears in print, this field indicates the name of the page on which the article is found. Please note that this field is intended for the exact page name (e.g. A5, B18).
 *
 *
 * -------------------------------- PrintSection ---------------------------------------------
 *
 * @property string PrintSection
 *
 * @method string getPrintSection() If this NewsArticle appears in print, this field indicates the print section in which the article appeared.
 *
 * @method NewsArticle setPrintSection(string $printSection )If this NewsArticle appears in print, this field indicates the print section in which the article appeared.
 *
 *
 */
class NewsArticle extends \Bordeux\SchemaOrg\Thing\CreativeWork\Article
{
}
