<?php

namespace Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/ImageObject
 *
 *
 * -------------------------------- Caption ---------------------------------------------
 *
 * @property string Caption
 *
 * @method string getCaption() The caption for this object.
 *
 * @method ImageObject setCaption(string $caption )The caption for this object.
 *
 *
 * -------------------------------- ExifData ---------------------------------------------
 *
 * @property string ExifData
 *
 * @method string getExifData() exif data for this object.
 *
 * @method ImageObject setExifData(string $exifData )exif data for this object.
 *
 *
 * -------------------------------- RepresentativeOfPage ---------------------------------------------
 *
 * @property Boolean RepresentativeOfPage
 *
 * @method Boolean getRepresentativeOfPage() Indicates whether this image is representative of the content of the page.
 *
 * @method ImageObject setRepresentativeOfPage(Boolean $representativeOfPage )Indicates whether this image is representative of the content of the page.
 *
 *
 * -------------------------------- Thumbnail ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\ImageObject Thumbnail
 *
 * @method \Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\ImageObject getThumbnail() Thumbnail image for an image or video.
 *
 * @method ImageObject setThumbnail(\Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\ImageObject $thumbnail )Thumbnail image for an image or video.
 *
 *
 */
class ImageObject extends \Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject
{
}
