<?php

namespace Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/VideoObject
 *
 *
 * -------------------------------- Caption ---------------------------------------------
 *
 * @property string Caption
 *
 * @method string getCaption() The caption for this object.
 *
 * @method VideoObject setCaption(string $caption )The caption for this object.
 *
 *
 * -------------------------------- Thumbnail ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\ImageObject Thumbnail
 *
 * @method \Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\ImageObject getThumbnail() Thumbnail image for an image or video.
 *
 * @method VideoObject setThumbnail(\Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\ImageObject $thumbnail )Thumbnail image for an image or video.
 *
 *
 * -------------------------------- Transcript ---------------------------------------------
 *
 * @property string Transcript
 *
 * @method string getTranscript() If this MediaObject is an AudioObject or VideoObject, the transcript of that object.
 *
 * @method VideoObject setTranscript(string $transcript )If this MediaObject is an AudioObject or VideoObject, the transcript of that object.
 *
 *
 * -------------------------------- VideoFrameSize ---------------------------------------------
 *
 * @property string VideoFrameSize
 *
 * @method string getVideoFrameSize() The frame size of the video.
 *
 * @method VideoObject setVideoFrameSize(string $videoFrameSize )The frame size of the video.
 *
 *
 * -------------------------------- VideoQuality ---------------------------------------------
 *
 * @property string VideoQuality
 *
 * @method string getVideoQuality() The quality of the video.
 *
 * @method VideoObject setVideoQuality(string $videoQuality )The quality of the video.
 *
 *
 */
class VideoObject extends \Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject
{
}
