<?php

namespace Bordeux\SchemaOrg\Thing\Intangible\Offer;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/AggregateOffer
 *
 *
 * -------------------------------- HighPrice ---------------------------------------------
 *
 * @property Number|string HighPrice
 *
 * @method Number|string getHighPrice() The highest price of all offers available.
 *
 * @method AggregateOffer setHighPrice(Number $highPrice ) setHighPrice(string $highPrice )The highest price of all offers available.
 *
 *
 * -------------------------------- LowPrice ---------------------------------------------
 *
 * @property Number|string LowPrice
 *
 * @method Number|string getLowPrice() The lowest price of all offers available.
 *
 * @method AggregateOffer setLowPrice(Number $lowPrice ) setLowPrice(string $lowPrice )The lowest price of all offers available.
 *
 *
 * -------------------------------- OfferCount ---------------------------------------------
 *
 * @property Integer OfferCount
 *
 * @method Integer getOfferCount() The number of offers for the product.
 *
 * @method AggregateOffer setOfferCount(Integer $offerCount )The number of offers for the product.
 *
 *
 */
class AggregateOffer extends \Bordeux\SchemaOrg\Thing\Intangible\Offer
{
}
