<?php

namespace Bordeux\SchemaOrg\Thing\Intangible\Audience;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/PeopleAudience
 *
 *
 * -------------------------------- HealthCondition ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalCondition HealthCondition
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalCondition getHealthCondition() Expectations for health conditions of target audience
 *
 * @method PeopleAudience setHealthCondition(\Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalCondition $healthCondition )Expectations for health conditions of target audience
 *
 *
 * -------------------------------- RequiredGender ---------------------------------------------
 *
 * @property string RequiredGender
 *
 * @method string getRequiredGender() Audiences defined by a person's gender.
 *
 * @method PeopleAudience setRequiredGender(string $requiredGender )Audiences defined by a person's gender.
 *
 *
 * -------------------------------- RequiredMaxAge ---------------------------------------------
 *
 * @property Integer RequiredMaxAge
 *
 * @method Integer getRequiredMaxAge() Audiences defined by a person's maximum age.
 *
 * @method PeopleAudience setRequiredMaxAge(Integer $requiredMaxAge )Audiences defined by a person's maximum age.
 *
 *
 * -------------------------------- RequiredMinAge ---------------------------------------------
 *
 * @property Integer RequiredMinAge
 *
 * @method Integer getRequiredMinAge() Audiences defined by a person's minimum age.
 *
 * @method PeopleAudience setRequiredMinAge(Integer $requiredMinAge )Audiences defined by a person's minimum age.
 *
 *
 * -------------------------------- SuggestedGender ---------------------------------------------
 *
 * @property string SuggestedGender
 *
 * @method string getSuggestedGender() The gender of the person or audience.
 *
 * @method PeopleAudience setSuggestedGender(string $suggestedGender )The gender of the person or audience.
 *
 *
 * -------------------------------- SuggestedMaxAge ---------------------------------------------
 *
 * @property Number SuggestedMaxAge
 *
 * @method Number getSuggestedMaxAge() Maximal age recommended for viewing content
 *
 * @method PeopleAudience setSuggestedMaxAge(Number $suggestedMaxAge )Maximal age recommended for viewing content
 *
 *
 * -------------------------------- SuggestedMinAge ---------------------------------------------
 *
 * @property Number SuggestedMinAge
 *
 * @method Number getSuggestedMinAge() Minimal age recommended for viewing content
 *
 * @method PeopleAudience setSuggestedMinAge(Number $suggestedMinAge )Minimal age recommended for viewing content
 *
 *
 */
class PeopleAudience extends \Bordeux\SchemaOrg\Thing\Intangible\Audience
{
}
