<?php

namespace Bordeux\SchemaOrg\Thing\Action\OrganizeAction;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/PlanAction
 *
 *
 * -------------------------------- ScheduledTime ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\SchemaDateTime ScheduledTime
 *
 * @method \Bordeux\SchemaOrg\SchemaDateTime getScheduledTime() The time the object is scheduled to.
 *
 * @method PlanAction setScheduledTime(\Bordeux\SchemaOrg\SchemaDateTime $scheduledTime )The time the object is scheduled to.
 *
 *
 */
class PlanAction extends \Bordeux\SchemaOrg\Thing\Action\OrganizeAction
{
}
