<?php

namespace Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalProcedure;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/DiagnosticProcedure
 *
 *
 * -------------------------------- AffectedBy ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalTherapy\Drug AffectedBy
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalTherapy\Drug getAffectedBy() Drugs that affect the test's results.
 *
 * @method DiagnosticProcedure setAffectedBy(\Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalTherapy\Drug $affectedBy )Drugs that affect the test's results.
 *
 *
 * -------------------------------- NormalRange ---------------------------------------------
 *
 * @property string NormalRange
 *
 * @method string getNormalRange() Range of acceptable values for a typical patient, when applicable.
 *
 * @method DiagnosticProcedure setNormalRange(string $normalRange )Range of acceptable values for a typical patient, when applicable.
 *
 *
 * -------------------------------- SignDetected ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalSignOrSymptom\MedicalSign SignDetected
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalSignOrSymptom\MedicalSign getSignDetected() A sign detected by the test.
 *
 * @method DiagnosticProcedure setSignDetected(\Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalSignOrSymptom\MedicalSign $signDetected )A sign detected by the test.
 *
 *
 * -------------------------------- UsedToDiagnose ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalCondition UsedToDiagnose
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalCondition getUsedToDiagnose() A condition the test is used to diagnose.
 *
 * @method DiagnosticProcedure setUsedToDiagnose(\Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalCondition $usedToDiagnose )A condition the test is used to diagnose.
 *
 *
 * -------------------------------- UsesDevice ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalDevice UsesDevice
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalDevice getUsesDevice() Device used to perform the test.
 *
 * @method DiagnosticProcedure setUsesDevice(\Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalDevice $usesDevice )Device used to perform the test.
 *
 *
 */
class DiagnosticProcedure extends \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalProcedure
{
}
