<?php

namespace Bordeux\SchemaOrg\Thing\CreativeWork\SoftwareApplication;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/WebApplication
 *
 *
 * -------------------------------- BrowserRequirements ---------------------------------------------
 *
 * @property string BrowserRequirements
 *
 * @method string getBrowserRequirements() Specifies browser requirements in human-readable text. For example,"requires HTML5 support".
 *
 * @method WebApplication setBrowserRequirements(string $browserRequirements )Specifies browser requirements in human-readable text. For example,"requires HTML5 support".
 *
 *
 */
class WebApplication extends \Bordeux\SchemaOrg\Thing\CreativeWork\SoftwareApplication
{
}
