<?php

namespace Bordeux\SchemaOrg\Thing\CreativeWork;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/DataCatalog
 *
 *
 * -------------------------------- Dataset ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\CreativeWork\Dataset Dataset
 *
 * @method \Bordeux\SchemaOrg\Thing\CreativeWork\Dataset getDataset() A dataset contained in a catalog.
 *
 * @method DataCatalog setDataset(\Bordeux\SchemaOrg\Thing\CreativeWork\Dataset $dataset )A dataset contained in a catalog.
 *
 *
 */
class DataCatalog extends \Bordeux\SchemaOrg\Thing\CreativeWork
{
}
