<?php

namespace Bordeux\SchemaOrg\Thing\Action;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/MoveAction
 *
 *
 * -------------------------------- FromLocation ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Place|Number FromLocation
 *
 * @method \Bordeux\SchemaOrg\Thing\Place|Number getFromLocation() A sub property of location. The original location of the object or the agent before the action.
 *
 * @method MoveAction setFromLocation(\Bordeux\SchemaOrg\Thing\Place $fromLocation ) setFromLocation(Number $fromLocation )A sub property of location. The original location of the object or the agent before the action.
 *
 *
 * -------------------------------- ToLocation ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Place|Number ToLocation
 *
 * @method \Bordeux\SchemaOrg\Thing\Place|Number getToLocation() A sub property of location. The final location of the object or the agent after the action.
 *
 * @method MoveAction setToLocation(\Bordeux\SchemaOrg\Thing\Place $toLocation ) setToLocation(Number $toLocation )A sub property of location. The final location of the object or the agent after the action.
 *
 *
 */
class MoveAction extends \Bordeux\SchemaOrg\Thing\Action
{
}
