<?php

namespace Bordeux\SchemaOrg\Thing\Intangible\Rating;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/AggregateRating
 *
 *
 * -------------------------------- ItemReviewed ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing ItemReviewed
 *
 * @method \Bordeux\SchemaOrg\Thing getItemReviewed() The item that is being reviewed/rated.
 *
 * @method AggregateRating setItemReviewed(\Bordeux\SchemaOrg\Thing $itemReviewed )The item that is being reviewed/rated.
 *
 *
 * -------------------------------- RatingCount ---------------------------------------------
 *
 * @property Number RatingCount
 *
 * @method Number getRatingCount() The count of total number of ratings.
 *
 * @method AggregateRating setRatingCount(Number $ratingCount )The count of total number of ratings.
 *
 *
 * -------------------------------- ReviewCount ---------------------------------------------
 *
 * @property Number ReviewCount
 *
 * @method Number getReviewCount() The count of total number of reviews.
 *
 * @method AggregateRating setReviewCount(Number $reviewCount )The count of total number of reviews.
 *
 *
 */
class AggregateRating extends \Bordeux\SchemaOrg\Thing\Intangible\Rating
{
}
