<?php

namespace Bordeux\SchemaOrg\Thing\Intangible\StructuredValue;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/GeoShape
 *
 *
 * -------------------------------- Box ---------------------------------------------
 *
 * @property string Box
 *
 * @method string getBox() A polygon is the area enclosed by a point-to-point path for which the starting and ending points are the same. A polygon is expressed as a series of four or more spacedelimited points where the first and final points are identical.
 *
 * @method GeoShape setBox(string $box )A polygon is the area enclosed by a point-to-point path for which the starting and ending points are the same. A polygon is expressed as a series of four or more spacedelimited points where the first and final points are identical.
 *
 *
 * -------------------------------- Circle ---------------------------------------------
 *
 * @property string Circle
 *
 * @method string getCircle() A circle is the circular region of a specified radius centered at a specified latitude and longitude. A circle is expressed as a pair followed by a radius in meters.
 *
 * @method GeoShape setCircle(string $circle )A circle is the circular region of a specified radius centered at a specified latitude and longitude. A circle is expressed as a pair followed by a radius in meters.
 *
 *
 * -------------------------------- Elevation ---------------------------------------------
 *
 * @property string|Number Elevation
 *
 * @method string|Number getElevation() The elevation of a location.
 *
 * @method GeoShape setElevation(string $elevation ) setElevation(Number $elevation )The elevation of a location.
 *
 *
 * -------------------------------- Line ---------------------------------------------
 *
 * @property string Line
 *
 * @method string getLine() A line is a point-to-point path consisting of two or more points. A line is expressed as a series of two or more point objects separated by space.
 *
 * @method GeoShape setLine(string $line )A line is a point-to-point path consisting of two or more points. A line is expressed as a series of two or more point objects separated by space.
 *
 *
 * -------------------------------- Polygon ---------------------------------------------
 *
 * @property string Polygon
 *
 * @method string getPolygon() A polygon is the area enclosed by a point-to-point path for which the starting and ending points are the same. A polygon is expressed as a series of four or more spacedelimited points where the first and final points are identical.
 *
 * @method GeoShape setPolygon(string $polygon )A polygon is the area enclosed by a point-to-point path for which the starting and ending points are the same. A polygon is expressed as a series of four or more spacedelimited points where the first and final points are identical.
 *
 *
 */
class GeoShape extends \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue
{
}
