<?php

namespace Bordeux\SchemaOrg\Thing\Intangible\StructuredValue;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/OpeningHoursSpecification
 *
 *
 * -------------------------------- Closes ---------------------------------------------
 *
 * @property Time Closes
 *
 * @method Time getCloses() The closing hour of the place or service on the given day(s) of the week.
 *
 * @method OpeningHoursSpecification setCloses(Time $closes )The closing hour of the place or service on the given day(s) of the week.
 *
 *
 * -------------------------------- DayOfWeek ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Enumeration\DayOfWeek DayOfWeek
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Enumeration\DayOfWeek getDayOfWeek() The day of the week for which these opening hours are valid.
 *
 * @method OpeningHoursSpecification setDayOfWeek(\Bordeux\SchemaOrg\Thing\Intangible\Enumeration\DayOfWeek $dayOfWeek )The day of the week for which these opening hours are valid.
 *
 *
 * -------------------------------- Opens ---------------------------------------------
 *
 * @property Time Opens
 *
 * @method Time getOpens() The opening hour of the place or service on the given day(s) of the week.
 *
 * @method OpeningHoursSpecification setOpens(Time $opens )The opening hour of the place or service on the given day(s) of the week.
 *
 *
 * -------------------------------- ValidFrom ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\SchemaDateTime ValidFrom
 *
 * @method \Bordeux\SchemaOrg\SchemaDateTime getValidFrom() The date when the item becomes valid.
 *
 * @method OpeningHoursSpecification setValidFrom(\Bordeux\SchemaOrg\SchemaDateTime $validFrom )The date when the item becomes valid.
 *
 *
 * -------------------------------- ValidThrough ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\SchemaDateTime ValidThrough
 *
 * @method \Bordeux\SchemaOrg\SchemaDateTime getValidThrough() The end of the validity of offer, price specification, or opening hours data.
 *
 * @method OpeningHoursSpecification setValidThrough(\Bordeux\SchemaOrg\SchemaDateTime $validThrough )The end of the validity of offer, price specification, or opening hours data.
 *
 *
 */
class OpeningHoursSpecification extends \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue
{
}
