<?php

namespace Bordeux\SchemaOrg\Thing\Action\TradeAction;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/SellAction
 *
 *
 * -------------------------------- Buyer ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Person Buyer
 *
 * @method \Bordeux\SchemaOrg\Thing\Person getBuyer() A sub property of participant. The participant/person/organization that bought the object.
 *
 * @method SellAction setBuyer(\Bordeux\SchemaOrg\Thing\Person $buyer )A sub property of participant. The participant/person/organization that bought the object.
 *
 *
 * -------------------------------- WarrantyPromise ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\WarrantyPromise WarrantyPromise
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\WarrantyPromise getWarrantyPromise() The warranty promise(s) included in the offer.
 *
 * @method SellAction setWarrantyPromise(\Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\WarrantyPromise $warrantyPromise )The warranty promise(s) included in the offer.
 *
 *
 */
class SellAction extends \Bordeux\SchemaOrg\Thing\Action\TradeAction
{
}
