<?php

namespace Bordeux\SchemaOrg\Thing\MedicalEntity;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/MedicalProcedure
 *
 *
 * -------------------------------- Followup ---------------------------------------------
 *
 * @property string Followup
 *
 * @method string getFollowup() Typical or recommended followup care after the procedure is performed.
 *
 * @method MedicalProcedure setFollowup(string $followup )Typical or recommended followup care after the procedure is performed.
 *
 *
 * -------------------------------- HowPerformed ---------------------------------------------
 *
 * @property string HowPerformed
 *
 * @method string getHowPerformed() How the procedure is performed.
 *
 * @method MedicalProcedure setHowPerformed(string $howPerformed )How the procedure is performed.
 *
 *
 * -------------------------------- Preparation ---------------------------------------------
 *
 * @property string Preparation
 *
 * @method string getPreparation() Typical preparation that a patient must undergo before having the procedure performed.
 *
 * @method MedicalProcedure setPreparation(string $preparation )Typical preparation that a patient must undergo before having the procedure performed.
 *
 *
 * -------------------------------- ProcedureType ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible\MedicalEnumeration\MedicalProcedureType ProcedureType
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible\MedicalEnumeration\MedicalProcedureType getProcedureType() The type of procedure, for example Surgical, Noninvasive, or Percutaneous.
 *
 * @method MedicalProcedure setProcedureType(\Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible\MedicalEnumeration\MedicalProcedureType $procedureType )The type of procedure, for example Surgical, Noninvasive, or Percutaneous.
 *
 *
 */
class MedicalProcedure extends \Bordeux\SchemaOrg\Thing\MedicalEntity
{
}
