<?php

namespace Bordeux\SchemaOrg\Thing\Action\AssessAction;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/ChooseAction
 *
 *
 * -------------------------------- Option ---------------------------------------------
 *
 * @property string|\Bordeux\SchemaOrg\Thing Option
 *
 * @method string|\Bordeux\SchemaOrg\Thing getOption() A sub property of object. The options subject to this action.
 *
 * @method ChooseAction setOption(string $option ) setOption(\Bordeux\SchemaOrg\Thing $option )A sub property of object. The options subject to this action.
 *
 *
 */
class ChooseAction extends \Bordeux\SchemaOrg\Thing\Action\AssessAction
{
}
