<?php

namespace Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalCondition;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/InfectiousDisease
 *
 *
 * -------------------------------- InfectiousAgent ---------------------------------------------
 *
 * @property string InfectiousAgent
 *
 * @method string getInfectiousAgent() The actual infectious agent, such as a specific bacterium.
 *
 * @method InfectiousDisease setInfectiousAgent(string $infectiousAgent )The actual infectious agent, such as a specific bacterium.
 *
 *
 * -------------------------------- InfectiousAgentClass ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible\MedicalEnumeration\InfectiousAgentClass InfectiousAgentClass
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible\MedicalEnumeration\InfectiousAgentClass getInfectiousAgentClass() The class of infectious agent (bacteria, prion, etc.) that causes the disease.
 *
 * @method InfectiousDisease setInfectiousAgentClass(\Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible\MedicalEnumeration\InfectiousAgentClass $infectiousAgentClass )The class of infectious agent (bacteria, prion, etc.) that causes the disease.
 *
 *
 * -------------------------------- TransmissionMethod ---------------------------------------------
 *
 * @property string TransmissionMethod
 *
 * @method string getTransmissionMethod() How the disease spreads, either as a route or vector, for example 'direct contact', 'Aedes aegypti', etc.
 *
 * @method InfectiousDisease setTransmissionMethod(string $transmissionMethod )How the disease spreads, either as a route or vector, for example 'direct contact', 'Aedes aegypti', etc.
 *
 *
 */
class InfectiousDisease extends \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalCondition
{
}
