<?php

namespace Bordeux\SchemaOrg\Thing\Action;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/SearchAction
 *
 *
 * -------------------------------- Query ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Class|string Query
 *
 * @method \Bordeux\SchemaOrg\Thing\Class|string getQuery() A sub property of instrument. The query used on this action.
 *
 * @method SearchAction setQuery(\Bordeux\SchemaOrg\Thing\Class $query ) setQuery(string $query )A sub property of instrument. The query used on this action.
 *
 *
 */
class SearchAction extends \Bordeux\SchemaOrg\Thing\Action
{
}
