<?php

namespace Bordeux\SchemaOrg\Thing;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/BroadcastService
 *
 *
 * -------------------------------- Area ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Place Area
 *
 * @method \Bordeux\SchemaOrg\Thing\Place getArea() The area within which users can expect to reach the broadcast service.
 *
 * @method BroadcastService setArea(\Bordeux\SchemaOrg\Thing\Place $area )The area within which users can expect to reach the broadcast service.
 *
 *
 * -------------------------------- Broadcaster ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Organization Broadcaster
 *
 * @method \Bordeux\SchemaOrg\Thing\Organization getBroadcaster() The organization owning or operating the broadcast service.
 *
 * @method BroadcastService setBroadcaster(\Bordeux\SchemaOrg\Thing\Organization $broadcaster )The organization owning or operating the broadcast service.
 *
 *
 * -------------------------------- ParentService ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\BroadcastService ParentService
 *
 * @method \Bordeux\SchemaOrg\Thing\BroadcastService getParentService() A broadcast service to which the broadcast service may belong to such as regional variations of a national channel.
 *
 * @method BroadcastService setParentService(\Bordeux\SchemaOrg\Thing\BroadcastService $parentService )A broadcast service to which the broadcast service may belong to such as regional variations of a national channel.
 *
 *
 */
class BroadcastService extends \Bordeux\SchemaOrg\Thing
{
}
