<?php

namespace Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalTherapy\LifestyleModification;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/PhysicalActivity
 *
 *
 * -------------------------------- AssociatedAnatomy ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalSystem|\Bordeux\SchemaOrg\Thing\MedicalEntity\SuperficialAnatomy|\Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalStructure AssociatedAnatomy
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalSystem|\Bordeux\SchemaOrg\Thing\MedicalEntity\SuperficialAnatomy|\Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalStructure getAssociatedAnatomy() The anatomy of the underlying organ system or structures associated with this entity.
 *
 * @method PhysicalActivity setAssociatedAnatomy(\Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalSystem $associatedAnatomy ) setAssociatedAnatomy(\Bordeux\SchemaOrg\Thing\MedicalEntity\SuperficialAnatomy $associatedAnatomy ) setAssociatedAnatomy(\Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalStructure $associatedAnatomy )The anatomy of the underlying organ system or structures associated with this entity.
 *
 *
 * -------------------------------- Category ---------------------------------------------
 *
 * @property string|\Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible\MedicalEnumeration\PhysicalActivityCategory|\Bordeux\SchemaOrg\Thing Category
 *
 * @method string|\Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible\MedicalEnumeration\PhysicalActivityCategory|\Bordeux\SchemaOrg\Thing getCategory() A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.
 *
 * @method PhysicalActivity setCategory(string $category ) setCategory(\Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible\MedicalEnumeration\PhysicalActivityCategory $category ) setCategory(\Bordeux\SchemaOrg\Thing $category )A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.
 *
 *
 * -------------------------------- Epidemiology ---------------------------------------------
 *
 * @property string Epidemiology
 *
 * @method string getEpidemiology() The characteristics of associated patients, such as age, gender, race etc.
 *
 * @method PhysicalActivity setEpidemiology(string $epidemiology )The characteristics of associated patients, such as age, gender, race etc.
 *
 *
 * -------------------------------- Pathophysiology ---------------------------------------------
 *
 * @property string Pathophysiology
 *
 * @method string getPathophysiology() Changes in the normal mechanical, physical, and biochemical functions that are associated with this activity or condition.
 *
 * @method PhysicalActivity setPathophysiology(string $pathophysiology )Changes in the normal mechanical, physical, and biochemical functions that are associated with this activity or condition.
 *
 *
 */
class PhysicalActivity extends \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalTherapy\LifestyleModification
{
}
