<?php

namespace Bordeux\SchemaOrg\Thing\Event;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/PublicationEvent
 *
 *
 * -------------------------------- Free ---------------------------------------------
 *
 * @property Boolean Free
 *
 * @method Boolean getFree() A flag to signal that the publication is accessible for free.
 *
 * @method PublicationEvent setFree(Boolean $free )A flag to signal that the publication is accessible for free.
 *
 *
 * -------------------------------- PublishedOn ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\BroadcastService PublishedOn
 *
 * @method \Bordeux\SchemaOrg\Thing\BroadcastService getPublishedOn() A broadcast service associated with the publication event
 *
 * @method PublicationEvent setPublishedOn(\Bordeux\SchemaOrg\Thing\BroadcastService $publishedOn )A broadcast service associated with the publication event
 *
 *
 */
class PublicationEvent extends \Bordeux\SchemaOrg\Thing\Event
{
}
