<?php

namespace Bordeux\SchemaOrg\Thing\Organization;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/EducationalOrganization
 *
 *
 * -------------------------------- Alumni ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Person Alumni
 *
 * @method \Bordeux\SchemaOrg\Thing\Person getAlumni() Alumni of educational organization.
 *
 * @method EducationalOrganization setAlumni(\Bordeux\SchemaOrg\Thing\Person $alumni )Alumni of educational organization.
 *
 *
 */
class EducationalOrganization extends \Bordeux\SchemaOrg\Thing\Organization
{
}
