<?php

namespace Bordeux\SchemaOrg\Thing\Action\UpdateAction;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/ReplaceAction
 *
 *
 * -------------------------------- Replacee ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing Replacee
 *
 * @method \Bordeux\SchemaOrg\Thing getReplacee() A sub property of object. The object that is being replaced.
 *
 * @method ReplaceAction setReplacee(\Bordeux\SchemaOrg\Thing $replacee )A sub property of object. The object that is being replaced.
 *
 *
 * -------------------------------- Replacer ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing Replacer
 *
 * @method \Bordeux\SchemaOrg\Thing getReplacer() A sub property of object. The object that replaces.
 *
 * @method ReplaceAction setReplacer(\Bordeux\SchemaOrg\Thing $replacer )A sub property of object. The object that replaces.
 *
 *
 */
class ReplaceAction extends \Bordeux\SchemaOrg\Thing\Action\UpdateAction
{
}
