<?php

namespace Bordeux\SchemaOrg\Thing\CreativeWork\Article\TechArticle;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/APIReference
 *
 *
 * -------------------------------- Assembly ---------------------------------------------
 *
 * @property string Assembly
 *
 * @method string getAssembly() Library file name e.g., mscorlib.dll, system.web.dll
 *
 * @method APIReference setAssembly(string $assembly )Library file name e.g., mscorlib.dll, system.web.dll
 *
 *
 * -------------------------------- AssemblyVersion ---------------------------------------------
 *
 * @property string AssemblyVersion
 *
 * @method string getAssemblyVersion() Associated product/technology version. e.g., .NET Framework 4.5
 *
 * @method APIReference setAssemblyVersion(string $assemblyVersion )Associated product/technology version. e.g., .NET Framework 4.5
 *
 *
 * -------------------------------- ProgrammingModel ---------------------------------------------
 *
 * @property string ProgrammingModel
 *
 * @method string getProgrammingModel() Indicates whether API is managed or unmanaged.
 *
 * @method APIReference setProgrammingModel(string $programmingModel )Indicates whether API is managed or unmanaged.
 *
 *
 * -------------------------------- TargetPlatform ---------------------------------------------
 *
 * @property string TargetPlatform
 *
 * @method string getTargetPlatform() Type of app development: phone, Metro style, desktop, XBox, etc.
 *
 * @method APIReference setTargetPlatform(string $targetPlatform )Type of app development: phone, Metro style, desktop, XBox, etc.
 *
 *
 */
class APIReference extends \Bordeux\SchemaOrg\Thing\CreativeWork\Article\TechArticle
{
}
