<?php

namespace Bordeux\SchemaOrg\Thing\Intangible\Audience\PeopleAudience;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/ParentAudience
 *
 *
 * -------------------------------- ChildMaxAge ---------------------------------------------
 *
 * @property Number ChildMaxAge
 *
 * @method Number getChildMaxAge() Maximal age of the child
 *
 * @method ParentAudience setChildMaxAge(Number $childMaxAge )Maximal age of the child
 *
 *
 * -------------------------------- ChildMinAge ---------------------------------------------
 *
 * @property Number ChildMinAge
 *
 * @method Number getChildMinAge() Minimal age of the child
 *
 * @method ParentAudience setChildMinAge(Number $childMinAge )Minimal age of the child
 *
 *
 */
class ParentAudience extends \Bordeux\SchemaOrg\Thing\Intangible\Audience\PeopleAudience
{
}
