<?php

namespace Bordeux\SchemaOrg\Thing\Action\InteractAction\CommunicateAction;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/AskAction
 *
 *
 * -------------------------------- Question ---------------------------------------------
 *
 * @property string Question
 *
 * @method string getQuestion() A sub property of object. A question.
 *
 * @method AskAction setQuestion(string $question )A sub property of object. A question.
 *
 *
 */
class AskAction extends \Bordeux\SchemaOrg\Thing\Action\InteractAction\CommunicateAction
{
}
