<?php

namespace Bordeux\SchemaOrg\Thing\Action\UpdateAction\AddAction;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/InsertAction
 *
 *
 * -------------------------------- ToLocation ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Place|Number ToLocation
 *
 * @method \Bordeux\SchemaOrg\Thing\Place|Number getToLocation() A sub property of location. The final location of the object or the agent after the action.
 *
 * @method InsertAction setToLocation(\Bordeux\SchemaOrg\Thing\Place $toLocation ) setToLocation(Number $toLocation )A sub property of location. The final location of the object or the agent after the action.
 *
 *
 */
class InsertAction extends \Bordeux\SchemaOrg\Thing\Action\UpdateAction\AddAction
{
}
