<?php

namespace Bordeux\SchemaOrg\Thing;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/Organization
 *
 *
 * -------------------------------- Address ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint\PostalAddress Address
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint\PostalAddress getAddress() Physical address of the item.
 *
 * @method Organization setAddress(\Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint\PostalAddress $address )Physical address of the item.
 *
 *
 * -------------------------------- AggregateRating ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Rating\AggregateRating AggregateRating
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Rating\AggregateRating getAggregateRating() The overall rating, based on a collection of reviews or ratings, of the item.
 *
 * @method Organization setAggregateRating(\Bordeux\SchemaOrg\Thing\Intangible\Rating\AggregateRating $aggregateRating )The overall rating, based on a collection of reviews or ratings, of the item.
 *
 *
 * -------------------------------- Brand ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Organization|\Bordeux\SchemaOrg\Thing\Intangible\Brand Brand
 *
 * @method \Bordeux\SchemaOrg\Thing\Organization|\Bordeux\SchemaOrg\Thing\Intangible\Brand getBrand() The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.
 *
 * @method Organization setBrand(\Bordeux\SchemaOrg\Thing\Organization $brand ) setBrand(\Bordeux\SchemaOrg\Thing\Intangible\Brand $brand )The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.
 *
 *
 * -------------------------------- ContactPoint ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint ContactPoint
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint getContactPoint() A contact point for a person or organization.
 *
 * @method Organization setContactPoint(\Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint $contactPoint )A contact point for a person or organization.
 *
 *
 * -------------------------------- ContactPoints ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint ContactPoints
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint getContactPoints() A contact point for a person or organization (legacy spelling; see singular form, contactPoint).
 *
 * @method Organization setContactPoints(\Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint $contactPoints )A contact point for a person or organization (legacy spelling; see singular form, contactPoint).
 *
 *
 * -------------------------------- Department ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Organization Department
 *
 * @method \Bordeux\SchemaOrg\Thing\Organization getDepartment() A relationship between an organization and a department of that organization, also described as an organization (allowing different urls, logos, opening hours). For example: a store with a pharmacy, or a bakery with a cafe.
 *
 * @method Organization setDepartment(\Bordeux\SchemaOrg\Thing\Organization $department )A relationship between an organization and a department of that organization, also described as an organization (allowing different urls, logos, opening hours). For example: a store with a pharmacy, or a bakery with a cafe.
 *
 *
 * -------------------------------- Duns ---------------------------------------------
 *
 * @property string Duns
 *
 * @method string getDuns() The Dun & Bradstreet DUNS number for identifying an organization or business person.
 *
 * @method Organization setDuns(string $duns )The Dun & Bradstreet DUNS number for identifying an organization or business person.
 *
 *
 * -------------------------------- Email ---------------------------------------------
 *
 * @property string Email
 *
 * @method string getEmail() Email address.
 *
 * @method Organization setEmail(string $email )Email address.
 *
 *
 * -------------------------------- Employee ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Person Employee
 *
 * @method \Bordeux\SchemaOrg\Thing\Person getEmployee() Someone working for this organization.
 *
 * @method Organization setEmployee(\Bordeux\SchemaOrg\Thing\Person $employee )Someone working for this organization.
 *
 *
 * -------------------------------- Employees ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Person Employees
 *
 * @method \Bordeux\SchemaOrg\Thing\Person getEmployees() People working for this organization. (legacy spelling; see singular form, employee)
 *
 * @method Organization setEmployees(\Bordeux\SchemaOrg\Thing\Person $employees )People working for this organization. (legacy spelling; see singular form, employee)
 *
 *
 * -------------------------------- Event ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Event Event
 *
 * @method \Bordeux\SchemaOrg\Thing\Event getEvent() Upcoming or past event associated with this place or organization.
 *
 * @method Organization setEvent(\Bordeux\SchemaOrg\Thing\Event $event )Upcoming or past event associated with this place or organization.
 *
 *
 * -------------------------------- Events ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Event Events
 *
 * @method \Bordeux\SchemaOrg\Thing\Event getEvents() Upcoming or past events associated with this place or organization (legacy spelling; see singular form, event).
 *
 * @method Organization setEvents(\Bordeux\SchemaOrg\Thing\Event $events )Upcoming or past events associated with this place or organization (legacy spelling; see singular form, event).
 *
 *
 * -------------------------------- FaxNumber ---------------------------------------------
 *
 * @property string FaxNumber
 *
 * @method string getFaxNumber() The fax number.
 *
 * @method Organization setFaxNumber(string $faxNumber )The fax number.
 *
 *
 * -------------------------------- Founder ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Person Founder
 *
 * @method \Bordeux\SchemaOrg\Thing\Person getFounder() A person who founded this organization.
 *
 * @method Organization setFounder(\Bordeux\SchemaOrg\Thing\Person $founder )A person who founded this organization.
 *
 *
 * -------------------------------- Founders ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Person Founders
 *
 * @method \Bordeux\SchemaOrg\Thing\Person getFounders() A person who founded this organization (legacy spelling; see singular form, founder).
 *
 * @method Organization setFounders(\Bordeux\SchemaOrg\Thing\Person $founders )A person who founded this organization (legacy spelling; see singular form, founder).
 *
 *
 * -------------------------------- FoundingDate ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\SchemaDateTime FoundingDate
 *
 * @method \Bordeux\SchemaOrg\SchemaDateTime getFoundingDate() The date that this organization was founded.
 *
 * @method Organization setFoundingDate(\Bordeux\SchemaOrg\SchemaDateTime $foundingDate )The date that this organization was founded.
 *
 *
 * -------------------------------- GlobalLocationNumber ---------------------------------------------
 *
 * @property string GlobalLocationNumber
 *
 * @method string getGlobalLocationNumber() The Global Location Number (GLN, sometimes also referred to as International Location Number or ILN) of the respective organization, person, or place. The GLN is a 13-digit number used to identify parties and physical locations.
 *
 * @method Organization setGlobalLocationNumber(string $globalLocationNumber )The Global Location Number (GLN, sometimes also referred to as International Location Number or ILN) of the respective organization, person, or place. The GLN is a 13-digit number used to identify parties and physical locations.
 *
 *
 * -------------------------------- HasPOS ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Place HasPOS
 *
 * @method \Bordeux\SchemaOrg\Thing\Place getHasPOS() Points-of-Sales operated by the organization or person.
 *
 * @method Organization setHasPOS(\Bordeux\SchemaOrg\Thing\Place $hasPOS )Points-of-Sales operated by the organization or person.
 *
 *
 * -------------------------------- InteractionCount ---------------------------------------------
 *
 * @property string InteractionCount
 *
 * @method string getInteractionCount() A count of a specific user interactions with this item—for example, 20 UserLikes, 5 UserComments, or 300 UserDownloads. The user interaction type should be one of the sub types of UserInteraction.
 *
 * @method Organization setInteractionCount(string $interactionCount )A count of a specific user interactions with this item—for example, 20 UserLikes, 5 UserComments, or 300 UserDownloads. The user interaction type should be one of the sub types of UserInteraction.
 *
 *
 * -------------------------------- IsicV4 ---------------------------------------------
 *
 * @property string IsicV4
 *
 * @method string getIsicV4() The International Standard of Industrial Classification of All Economic Activities (ISIC), Revision 4 code for a particular organization, business person, or place.
 *
 * @method Organization setIsicV4(string $isicV4 )The International Standard of Industrial Classification of All Economic Activities (ISIC), Revision 4 code for a particular organization, business person, or place.
 *
 *
 * -------------------------------- LegalName ---------------------------------------------
 *
 * @property string LegalName
 *
 * @method string getLegalName() The official name of the organization, e.g. the registered company name.
 *
 * @method Organization setLegalName(string $legalName )The official name of the organization, e.g. the registered company name.
 *
 *
 * -------------------------------- Location ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint\PostalAddress|\Bordeux\SchemaOrg\Thing\Place Location
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint\PostalAddress|\Bordeux\SchemaOrg\Thing\Place getLocation() The location of the event, organization or action.
 *
 * @method Organization setLocation(\Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint\PostalAddress $location ) setLocation(\Bordeux\SchemaOrg\Thing\Place $location )The location of the event, organization or action.
 *
 *
 * -------------------------------- Logo ---------------------------------------------
 *
 * @property string|\Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\ImageObject Logo
 *
 * @method string|\Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\ImageObject getLogo() A logo associated with an organization.
 *
 * @method Organization setLogo(string $logo ) setLogo(\Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\ImageObject $logo )A logo associated with an organization.
 *
 *
 * -------------------------------- MakesOffer ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Offer MakesOffer
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Offer getMakesOffer() A pointer to products or services offered by the organization or person.
 *
 * @method Organization setMakesOffer(\Bordeux\SchemaOrg\Thing\Intangible\Offer $makesOffer )A pointer to products or services offered by the organization or person.
 *
 *
 * -------------------------------- Member ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Organization|\Bordeux\SchemaOrg\Thing\Person Member
 *
 * @method \Bordeux\SchemaOrg\Thing\Organization|\Bordeux\SchemaOrg\Thing\Person getMember() A member of this organization.
 *
 * @method Organization setMember(\Bordeux\SchemaOrg\Thing\Organization $member ) setMember(\Bordeux\SchemaOrg\Thing\Person $member )A member of this organization.
 *
 *
 * -------------------------------- Members ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Organization|\Bordeux\SchemaOrg\Thing\Person Members
 *
 * @method \Bordeux\SchemaOrg\Thing\Organization|\Bordeux\SchemaOrg\Thing\Person getMembers() A member of this organization (legacy spelling; see singular form, member).
 *
 * @method Organization setMembers(\Bordeux\SchemaOrg\Thing\Organization $members ) setMembers(\Bordeux\SchemaOrg\Thing\Person $members )A member of this organization (legacy spelling; see singular form, member).
 *
 *
 * -------------------------------- Naics ---------------------------------------------
 *
 * @property string Naics
 *
 * @method string getNaics() The North American Industry Classification System (NAICS) code for a particular organization or business person.
 *
 * @method Organization setNaics(string $naics )The North American Industry Classification System (NAICS) code for a particular organization or business person.
 *
 *
 * -------------------------------- Owns ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\OwnershipInfo|\Bordeux\SchemaOrg\Thing\Product Owns
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\OwnershipInfo|\Bordeux\SchemaOrg\Thing\Product getOwns() Products owned by the organization or person.
 *
 * @method Organization setOwns(\Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\OwnershipInfo $owns ) setOwns(\Bordeux\SchemaOrg\Thing\Product $owns )Products owned by the organization or person.
 *
 *
 * -------------------------------- Review ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\CreativeWork\Review Review
 *
 * @method \Bordeux\SchemaOrg\Thing\CreativeWork\Review getReview() A review of the item.
 *
 * @method Organization setReview(\Bordeux\SchemaOrg\Thing\CreativeWork\Review $review )A review of the item.
 *
 *
 * -------------------------------- Reviews ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\CreativeWork\Review Reviews
 *
 * @method \Bordeux\SchemaOrg\Thing\CreativeWork\Review getReviews() Review of the item (legacy spelling; see singular form, review).
 *
 * @method Organization setReviews(\Bordeux\SchemaOrg\Thing\CreativeWork\Review $reviews )Review of the item (legacy spelling; see singular form, review).
 *
 *
 * -------------------------------- Seeks ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Demand Seeks
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Demand getSeeks() A pointer to products or services sought by the organization or person (demand).
 *
 * @method Organization setSeeks(\Bordeux\SchemaOrg\Thing\Intangible\Demand $seeks )A pointer to products or services sought by the organization or person (demand).
 *
 *
 * -------------------------------- SubOrganization ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Organization SubOrganization
 *
 * @method \Bordeux\SchemaOrg\Thing\Organization getSubOrganization() A relationship between two organizations where the first includes the second, e.g., as a subsidiary. See also: the more specific 'department' property.
 *
 * @method Organization setSubOrganization(\Bordeux\SchemaOrg\Thing\Organization $subOrganization )A relationship between two organizations where the first includes the second, e.g., as a subsidiary. See also: the more specific 'department' property.
 *
 *
 * -------------------------------- TaxID ---------------------------------------------
 *
 * @property string TaxID
 *
 * @method string getTaxID() The Tax / Fiscal ID of the organization or person, e.g. the TIN in the US or the CIF/NIF in Spain.
 *
 * @method Organization setTaxID(string $taxID )The Tax / Fiscal ID of the organization or person, e.g. the TIN in the US or the CIF/NIF in Spain.
 *
 *
 * -------------------------------- Telephone ---------------------------------------------
 *
 * @property string Telephone
 *
 * @method string getTelephone() The telephone number.
 *
 * @method Organization setTelephone(string $telephone )The telephone number.
 *
 *
 * -------------------------------- VatID ---------------------------------------------
 *
 * @property string VatID
 *
 * @method string getVatID() The Value-added Tax ID of the organisation or person.
 *
 * @method Organization setVatID(string $vatID )The Value-added Tax ID of the organisation or person.
 *
 *
 */
class Organization extends \Bordeux\SchemaOrg\Thing
{
}
