<?php

namespace Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/DoseSchedule
 *
 *
 * -------------------------------- DoseUnit ---------------------------------------------
 *
 * @property string DoseUnit
 *
 * @method string getDoseUnit() The unit of the dose, e.g. 'mg'.
 *
 * @method DoseSchedule setDoseUnit(string $doseUnit )The unit of the dose, e.g. 'mg'.
 *
 *
 * -------------------------------- DoseValue ---------------------------------------------
 *
 * @property Number DoseValue
 *
 * @method Number getDoseValue() The value of the dose, e.g. 500.
 *
 * @method DoseSchedule setDoseValue(Number $doseValue )The value of the dose, e.g. 500.
 *
 *
 * -------------------------------- Frequency ---------------------------------------------
 *
 * @property string Frequency
 *
 * @method string getFrequency() How often the dose is taken, e.g. 'daily'.
 *
 * @method DoseSchedule setFrequency(string $frequency )How often the dose is taken, e.g. 'daily'.
 *
 *
 * -------------------------------- TargetPopulation ---------------------------------------------
 *
 * @property string TargetPopulation
 *
 * @method string getTargetPopulation() Characteristics of the population for which this is intended, or which typically uses it, e.g. 'adults'.
 *
 * @method DoseSchedule setTargetPopulation(string $targetPopulation )Characteristics of the population for which this is intended, or which typically uses it, e.g. 'adults'.
 *
 *
 */
class DoseSchedule extends \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible
{
}
