<?php

namespace Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/DrugStrength
 *
 *
 * -------------------------------- ActiveIngredient ---------------------------------------------
 *
 * @property string ActiveIngredient
 *
 * @method string getActiveIngredient() An active ingredient, typically chemical compounds and/or biologic substances.
 *
 * @method DrugStrength setActiveIngredient(string $activeIngredient )An active ingredient, typically chemical compounds and/or biologic substances.
 *
 *
 * -------------------------------- AvailableIn ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Place\AdministrativeArea AvailableIn
 *
 * @method \Bordeux\SchemaOrg\Thing\Place\AdministrativeArea getAvailableIn() The location in which the strength is available.
 *
 * @method DrugStrength setAvailableIn(\Bordeux\SchemaOrg\Thing\Place\AdministrativeArea $availableIn )The location in which the strength is available.
 *
 *
 * -------------------------------- StrengthUnit ---------------------------------------------
 *
 * @property string StrengthUnit
 *
 * @method string getStrengthUnit() The units of an active ingredient's strength, e.g. mg.
 *
 * @method DrugStrength setStrengthUnit(string $strengthUnit )The units of an active ingredient's strength, e.g. mg.
 *
 *
 * -------------------------------- StrengthValue ---------------------------------------------
 *
 * @property Number StrengthValue
 *
 * @method Number getStrengthValue() The value of an active ingredient's strength, e.g. 325.
 *
 * @method DrugStrength setStrengthValue(Number $strengthValue )The value of an active ingredient's strength, e.g. 325.
 *
 *
 */
class DrugStrength extends \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible
{
}
