<?php

namespace Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/MedicalConditionStage
 *
 *
 * -------------------------------- StageAsNumber ---------------------------------------------
 *
 * @property Number StageAsNumber
 *
 * @method Number getStageAsNumber() The stage represented as a number, e.g. 3.
 *
 * @method MedicalConditionStage setStageAsNumber(Number $stageAsNumber )The stage represented as a number, e.g. 3.
 *
 *
 * -------------------------------- SubStageSuffix ---------------------------------------------
 *
 * @property string SubStageSuffix
 *
 * @method string getSubStageSuffix() The substage, e.g. 'a' for Stage IIIa.
 *
 * @method MedicalConditionStage setSubStageSuffix(string $subStageSuffix )The substage, e.g. 'a' for Stage IIIa.
 *
 *
 */
class MedicalConditionStage extends \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible
{
}
