<?php

namespace Bordeux\SchemaOrg\Thing\MedicalEntity;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/AnatomicalStructure
 *
 *
 * -------------------------------- AssociatedPathophysiology ---------------------------------------------
 *
 * @property string AssociatedPathophysiology
 *
 * @method string getAssociatedPathophysiology() If applicable, a description of the pathophysiology associated with the anatomical system, including potential abnormal changes in the mechanical, physical, and biochemical functions of the system.
 *
 * @method AnatomicalStructure setAssociatedPathophysiology(string $associatedPathophysiology )If applicable, a description of the pathophysiology associated with the anatomical system, including potential abnormal changes in the mechanical, physical, and biochemical functions of the system.
 *
 *
 * -------------------------------- BodyLocation ---------------------------------------------
 *
 * @property string BodyLocation
 *
 * @method string getBodyLocation() Location in the body of the anatomical structure.
 *
 * @method AnatomicalStructure setBodyLocation(string $bodyLocation )Location in the body of the anatomical structure.
 *
 *
 * -------------------------------- ConnectedTo ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalStructure ConnectedTo
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalStructure getConnectedTo() Other anatomical structures to which this structure is connected.
 *
 * @method AnatomicalStructure setConnectedTo(\Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalStructure $connectedTo )Other anatomical structures to which this structure is connected.
 *
 *
 * -------------------------------- Diagram ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\ImageObject Diagram
 *
 * @method \Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\ImageObject getDiagram() An image containing a diagram that illustrates the structure and/or its component substructures and/or connections with other structures.
 *
 * @method AnatomicalStructure setDiagram(\Bordeux\SchemaOrg\Thing\CreativeWork\MediaObject\ImageObject $diagram )An image containing a diagram that illustrates the structure and/or its component substructures and/or connections with other structures.
 *
 *
 * -------------------------------- Function ---------------------------------------------
 *
 * @property string Function
 *
 * @method string getFunction() Function of the anatomical structure.
 *
 * @method AnatomicalStructure setFunction(string $function )Function of the anatomical structure.
 *
 *
 * -------------------------------- PartOfSystem ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalSystem PartOfSystem
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalSystem getPartOfSystem() The anatomical or organ system that this structure is part of.
 *
 * @method AnatomicalStructure setPartOfSystem(\Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalSystem $partOfSystem )The anatomical or organ system that this structure is part of.
 *
 *
 * -------------------------------- RelatedCondition ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalCondition RelatedCondition
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalCondition getRelatedCondition() A medical condition associated with this anatomy.
 *
 * @method AnatomicalStructure setRelatedCondition(\Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalCondition $relatedCondition )A medical condition associated with this anatomy.
 *
 *
 * -------------------------------- RelatedTherapy ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalTherapy RelatedTherapy
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalTherapy getRelatedTherapy() A medical therapy related to this anatomy.
 *
 * @method AnatomicalStructure setRelatedTherapy(\Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalTherapy $relatedTherapy )A medical therapy related to this anatomy.
 *
 *
 * -------------------------------- SubStructure ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalStructure SubStructure
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalStructure getSubStructure() Component (sub-)structure(s) that comprise this anatomical structure.
 *
 * @method AnatomicalStructure setSubStructure(\Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalStructure $subStructure )Component (sub-)structure(s) that comprise this anatomical structure.
 *
 *
 */
class AnatomicalStructure extends \Bordeux\SchemaOrg\Thing\MedicalEntity
{
}
