<?php

namespace Bordeux\SchemaOrg\Thing\MedicalEntity;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/MedicalStudy
 *
 *
 * -------------------------------- Outcome ---------------------------------------------
 *
 * @property string Outcome
 *
 * @method string getOutcome() Expected or actual outcomes of the study.
 *
 * @method MedicalStudy setOutcome(string $outcome )Expected or actual outcomes of the study.
 *
 *
 * -------------------------------- Population ---------------------------------------------
 *
 * @property string Population
 *
 * @method string getPopulation() Any characteristics of the population used in the study, e.g. 'males under 65'.
 *
 * @method MedicalStudy setPopulation(string $population )Any characteristics of the population used in the study, e.g. 'males under 65'.
 *
 *
 * -------------------------------- Sponsor ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Organization Sponsor
 *
 * @method \Bordeux\SchemaOrg\Thing\Organization getSponsor() Sponsor of the study.
 *
 * @method MedicalStudy setSponsor(\Bordeux\SchemaOrg\Thing\Organization $sponsor )Sponsor of the study.
 *
 *
 * -------------------------------- Status ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible\MedicalEnumeration\MedicalStudyStatus Status
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible\MedicalEnumeration\MedicalStudyStatus getStatus() The status of the study (enumerated).
 *
 * @method MedicalStudy setStatus(\Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalIntangible\MedicalEnumeration\MedicalStudyStatus $status )The status of the study (enumerated).
 *
 *
 * -------------------------------- StudyLocation ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Place\AdministrativeArea StudyLocation
 *
 * @method \Bordeux\SchemaOrg\Thing\Place\AdministrativeArea getStudyLocation() The location in which the study is taking/took place.
 *
 * @method MedicalStudy setStudyLocation(\Bordeux\SchemaOrg\Thing\Place\AdministrativeArea $studyLocation )The location in which the study is taking/took place.
 *
 *
 * -------------------------------- StudySubject ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity StudySubject
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity getStudySubject() A subject of the study, i.e. one of the medical conditions, therapies, devices, drugs, etc. investigated by the study.
 *
 * @method MedicalStudy setStudySubject(\Bordeux\SchemaOrg\Thing\MedicalEntity $studySubject )A subject of the study, i.e. one of the medical conditions, therapies, devices, drugs, etc. investigated by the study.
 *
 *
 */
class MedicalStudy extends \Bordeux\SchemaOrg\Thing\MedicalEntity
{
}
