<?php

namespace Bordeux\SchemaOrg\Thing\MedicalEntity;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/SuperficialAnatomy
 *
 *
 * -------------------------------- AssociatedPathophysiology ---------------------------------------------
 *
 * @property string AssociatedPathophysiology
 *
 * @method string getAssociatedPathophysiology() If applicable, a description of the pathophysiology associated with the anatomical system, including potential abnormal changes in the mechanical, physical, and biochemical functions of the system.
 *
 * @method SuperficialAnatomy setAssociatedPathophysiology(string $associatedPathophysiology )If applicable, a description of the pathophysiology associated with the anatomical system, including potential abnormal changes in the mechanical, physical, and biochemical functions of the system.
 *
 *
 * -------------------------------- RelatedAnatomy ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalStructure|\Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalSystem RelatedAnatomy
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalStructure|\Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalSystem getRelatedAnatomy() Anatomical systems or structures that relate to the superficial anatomy.
 *
 * @method SuperficialAnatomy setRelatedAnatomy(\Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalStructure $relatedAnatomy ) setRelatedAnatomy(\Bordeux\SchemaOrg\Thing\MedicalEntity\AnatomicalSystem $relatedAnatomy )Anatomical systems or structures that relate to the superficial anatomy.
 *
 *
 * -------------------------------- RelatedCondition ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalCondition RelatedCondition
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalCondition getRelatedCondition() A medical condition associated with this anatomy.
 *
 * @method SuperficialAnatomy setRelatedCondition(\Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalCondition $relatedCondition )A medical condition associated with this anatomy.
 *
 *
 * -------------------------------- RelatedTherapy ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalTherapy RelatedTherapy
 *
 * @method \Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalTherapy getRelatedTherapy() A medical therapy related to this anatomy.
 *
 * @method SuperficialAnatomy setRelatedTherapy(\Bordeux\SchemaOrg\Thing\MedicalEntity\MedicalTherapy $relatedTherapy )A medical therapy related to this anatomy.
 *
 *
 * -------------------------------- Significance ---------------------------------------------
 *
 * @property string Significance
 *
 * @method string getSignificance() The significance associated with the superficial anatomy; as an example, how characteristics of the superficial anatomy can suggest underlying medical conditions or courses of treatment.
 *
 * @method SuperficialAnatomy setSignificance(string $significance )The significance associated with the superficial anatomy; as an example, how characteristics of the superficial anatomy can suggest underlying medical conditions or courses of treatment.
 *
 *
 */
class SuperficialAnatomy extends \Bordeux\SchemaOrg\Thing\MedicalEntity
{
}
