<?php

namespace Bordeux\SchemaOrg\Thing\Intangible;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/AlignmentObject
 *
 *
 * -------------------------------- AlignmentType ---------------------------------------------
 *
 * @property string AlignmentType
 *
 * @method string getAlignmentType() A category of alignment between the learning resource and the framework node. Recommended values include: 'assesses', 'teaches', 'requires', 'textComplexity', 'readingLevel', 'educationalSubject', and 'educationLevel'.
 *
 * @method AlignmentObject setAlignmentType(string $alignmentType )A category of alignment between the learning resource and the framework node. Recommended values include: 'assesses', 'teaches', 'requires', 'textComplexity', 'readingLevel', 'educationalSubject', and 'educationLevel'.
 *
 *
 * -------------------------------- EducationalFramework ---------------------------------------------
 *
 * @property string EducationalFramework
 *
 * @method string getEducationalFramework() The framework to which the resource being described is aligned.
 *
 * @method AlignmentObject setEducationalFramework(string $educationalFramework )The framework to which the resource being described is aligned.
 *
 *
 * -------------------------------- TargetDescription ---------------------------------------------
 *
 * @property string TargetDescription
 *
 * @method string getTargetDescription() The description of a node in an established educational framework.
 *
 * @method AlignmentObject setTargetDescription(string $targetDescription )The description of a node in an established educational framework.
 *
 *
 * -------------------------------- TargetName ---------------------------------------------
 *
 * @property string TargetName
 *
 * @method string getTargetName() The name of a node in an established educational framework.
 *
 * @method AlignmentObject setTargetName(string $targetName )The name of a node in an established educational framework.
 *
 *
 * -------------------------------- TargetUrl ---------------------------------------------
 *
 * @property string TargetUrl
 *
 * @method string getTargetUrl() The URL of a node in an established educational framework.
 *
 * @method AlignmentObject setTargetUrl(string $targetUrl )The URL of a node in an established educational framework.
 *
 *
 */
class AlignmentObject extends \Bordeux\SchemaOrg\Thing\Intangible
{
}
