<?php

namespace Bordeux\SchemaOrg\Thing\Intangible;

/**
 * Generated by bordeux/schema
 *
 * @author Krzysztof Bednarczyk <schema@bordeux.net>
 * @link http://schema.org/ParcelDelivery
 *
 *
 * -------------------------------- Carrier ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Organization Carrier
 *
 * @method \Bordeux\SchemaOrg\Thing\Organization getCarrier() The party responsible for the parcel delivery.
 *
 * @method ParcelDelivery setCarrier(\Bordeux\SchemaOrg\Thing\Organization $carrier )The party responsible for the parcel delivery.
 *
 *
 * -------------------------------- DeliveryAddress ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint\PostalAddress DeliveryAddress
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint\PostalAddress getDeliveryAddress() Destination address.
 *
 * @method ParcelDelivery setDeliveryAddress(\Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint\PostalAddress $deliveryAddress )Destination address.
 *
 *
 * -------------------------------- DeliveryStatus ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Event\DeliveryEvent DeliveryStatus
 *
 * @method \Bordeux\SchemaOrg\Thing\Event\DeliveryEvent getDeliveryStatus() New entry added as the package passes through each leg of its journey (from shipment to final delivery).
 *
 * @method ParcelDelivery setDeliveryStatus(\Bordeux\SchemaOrg\Thing\Event\DeliveryEvent $deliveryStatus )New entry added as the package passes through each leg of its journey (from shipment to final delivery).
 *
 *
 * -------------------------------- ExpectedArrivalFrom ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\SchemaDateTime ExpectedArrivalFrom
 *
 * @method \Bordeux\SchemaOrg\SchemaDateTime getExpectedArrivalFrom() The earliest date the package may arrive.
 *
 * @method ParcelDelivery setExpectedArrivalFrom(\Bordeux\SchemaOrg\SchemaDateTime $expectedArrivalFrom )The earliest date the package may arrive.
 *
 *
 * -------------------------------- ExpectedArrivalUntil ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\SchemaDateTime ExpectedArrivalUntil
 *
 * @method \Bordeux\SchemaOrg\SchemaDateTime getExpectedArrivalUntil() The latest date the package may arrive.
 *
 * @method ParcelDelivery setExpectedArrivalUntil(\Bordeux\SchemaOrg\SchemaDateTime $expectedArrivalUntil )The latest date the package may arrive.
 *
 *
 * -------------------------------- HasDeliveryMethod ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Enumeration\DeliveryMethod HasDeliveryMethod
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Enumeration\DeliveryMethod getHasDeliveryMethod() Method used for delivery or shipping.
 *
 * @method ParcelDelivery setHasDeliveryMethod(\Bordeux\SchemaOrg\Thing\Intangible\Enumeration\DeliveryMethod $hasDeliveryMethod )Method used for delivery or shipping.
 *
 *
 * -------------------------------- ItemShipped ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Product ItemShipped
 *
 * @method \Bordeux\SchemaOrg\Thing\Product getItemShipped() Item(s) being shipped.
 *
 * @method ParcelDelivery setItemShipped(\Bordeux\SchemaOrg\Thing\Product $itemShipped )Item(s) being shipped.
 *
 *
 * -------------------------------- OriginAddress ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint\PostalAddress OriginAddress
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint\PostalAddress getOriginAddress() Shipper's address.
 *
 * @method ParcelDelivery setOriginAddress(\Bordeux\SchemaOrg\Thing\Intangible\StructuredValue\ContactPoint\PostalAddress $originAddress )Shipper's address.
 *
 *
 * -------------------------------- PartOfOrder ---------------------------------------------
 *
 * @property \Bordeux\SchemaOrg\Thing\Intangible\Order PartOfOrder
 *
 * @method \Bordeux\SchemaOrg\Thing\Intangible\Order getPartOfOrder() The overall order the items in this delivery were included in.
 *
 * @method ParcelDelivery setPartOfOrder(\Bordeux\SchemaOrg\Thing\Intangible\Order $partOfOrder )The overall order the items in this delivery were included in.
 *
 *
 * -------------------------------- TrackingNumber ---------------------------------------------
 *
 * @property string TrackingNumber
 *
 * @method string getTrackingNumber() Shipper tracking number.
 *
 * @method ParcelDelivery setTrackingNumber(string $trackingNumber )Shipper tracking number.
 *
 *
 * -------------------------------- TrackingUrl ---------------------------------------------
 *
 * @property string TrackingUrl
 *
 * @method string getTrackingUrl() Tracking url for the parcel delivery.
 *
 * @method ParcelDelivery setTrackingUrl(string $trackingUrl )Tracking url for the parcel delivery.
 *
 *
 */
class ParcelDelivery extends \Bordeux\SchemaOrg\Thing\Intangible
{
}
